version: '3.9'

services:
  # host/victim container
  kali-box:
    container_name: kali-box
    # image: ubuntu
    build:
      context: .
      # dockerfile: Dockerfile-ubuntu
    ports:
      - "2201:22"
    hostname: kali-box
    command: "sleep 1000000"
    volumes:
      - /Users/annika/Documents/kali:/pink


networks:
  default:
    name: kali
    external: true